version: '3'

services:
  app:
    image: 'nginx'
    container_name: cmlink
    restart: unless-stopped
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html